name: git-pr-release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # PRの存在チェックには最新のコミット情報のみあれば良い

      - name: Check if PR exists from develop to main
        id: check_pr
        run: |
          PR_NUMBER=$(gh pr list --base main --head develop --json number -q ".[].number")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from develop to main if not exists
        if: env.PR_NUMBER == ''
        run: |
          gh pr create --base main --head develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR description
        run: |
          PR_NUMBER=$(gh pr list --base main --head develop --json number -q ".[].number")

          inpact_list="$(gh pr list --base develop --state merged --search "-1 本番影響なし" --json url --template '{{range .}}{{.url}}{{"\n"}}{{end}}')";
          no_inpact_list="$(gh pr list --base develop --state merged --search "1 本番影響なし" --json url --template '{{range .}}{{.url}}{{"\n"}}{{end}}')";

          PR_DESCRIPTION=$(cat <<'EOF'
          - [ ] pilot 反映済み
          
          ---
          
          ## 銘柄
          
          > [!WARNING]
          >
          > 本番影響がないこと, dev*・pilot環境で問題ないことを確認済みで release しても問題ない場合は check を入れてください。
          > 
          > [リリース体制について](https://zozo.rickcloud.jp/wiki/pages/viewpage.action?pageId=346445078#:~:text=%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E4%BD%93%E5%88%B6)

          ### 本番影響あり
          
          $inpact_list

          ### 本番影響なし
          
          $no_inpact_list
          
          EOF
          )
          
          gh pr edit "$PR_NUMBER" --title "Release $(date)" --body "$PR_DESCRIPTION" # GitHub CLIを使ってPRの概要を更新する
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
