name: git-pr-release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # PRの存在チェックには最新のコミット情報のみあれば良い

      - name: Check if PR exists from develop to main
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base main --head develop --json number -q ".[].number")
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from develop to main if not exists
        if: env.PR_EXISTS == ''
        run: |
          gh pr create --base main --head develop --title "Release $(date)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false # このコマンドが失敗した場合は、ワークフローを停止する

      - name: Update PR description
        run: |
          gh pr edit "$PR_EXISTS" --title "$(date)" --body "Updated PR description" # GitHub CLIを使ってPRの概要を更新する
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
