name: git-pr-release

on:
  push:
    branches:
      - develop
      - 'feature/maintenance-**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  develop-to-main:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # PRの存在チェックには最新のコミット情報のみあれば良い

      - name: Set base and head branches for PR
        run: |
          echo "BASE_BRANCH=main" >> $GITHUB_ENV
          echo "HEAD_BRANCH=develop" >> $GITHUB_ENV

      - name: Check if PR exists between base and head
        run: |
          PR_NUMBER=$(gh pr list --base $BASE_BRANCH --head $HEAD_BRANCH --json number -q ".[].number")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR if not exists
        if: env.PR_NUMBER == ''
        run: |
          PR_CREATE_OUTPUT=$(gh pr create --base $BASE_BRANCH --head $HEAD_BRANCH --title "Auto PR by git-pr-release" --body "Automatically generated PR.")
          echo "$PR_CREATE_OUTPUT"

          # 新しいPRの番号を抽出して環境変数に設定
          PR_NUMBER=$(echo "$PR_CREATE_OUTPUT" | grep -o 'https://github.com/.*/pull/[0-9]*' | grep -o '[0-9]*$')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR description
        if: env.PR_NUMBER != ''
        run: |
          # git fetch origin

          # PRがmainブランチにマージされているかチェックする関数
          check_pr_merged_to_main() {
            local pr_number=$1
            local is_merged=$(git log origin/main --grep "Merge pull request #$pr_number" --oneline)
            if [[ -z "$is_merged" ]]; then
              echo "#$pr_number"
            fi
          }
          
          # 本番影響ありのPRをチェック
          impact_prs=$(gh pr list --base develop --state merged --search '-label:"1 本番影響なし"' --json number --template '{{range .}}{{.number}}{{"\n"}}{{end}}')
          
          # 本番影響なしのPRをチェック
          no_impact_prs=$(gh pr list --base develop --state merged --search 'label:"1 本番影響なし"' --json number --template '{{range .}}{{.number}}{{"\n"}}{{end}}')
          
          PR_DESCRIPTION=$(cat <<EOF

          - [ ] pilot 反映済み
          
          ---
          
          ## 銘柄
          > [!WARNING]
          >
          > 本番影響がないこと, dev*・pilot環境で問題ないことを確認済みで release しても問題ない場合は check を入れてください。
          > 
          > [リリース体制について](https://zozo.rickcloud.jp/wiki/x/FlWmF#:~:text=%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E4%BD%93%E5%88%B6)

          ### 本番影響あり
          $(for pr in $impact_prs; do check_pr_merged_to_main "$pr"; done)
          
          ### 本番影響なし
          $(for pr in $no_impact_prs; do check_pr_merged_to_main "$pr"; done)

          EOF
          )

          CURRENT_DATE=$(TZ='Asia/Tokyo' date "+%Y/%m/%d %H:%M")
          gh pr edit "$PR_NUMBER" --title "Release $CURRENT_DATE" --body "$PR_DESCRIPTION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  maintenance-to-develop:
    if: startsWith(github.ref, 'refs/heads/feature/maintenance-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # PRの存在チェックには最新のコミット情報のみあれば良い

      - name: Set base and head branches for PR
        run: |
          HEAD_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "BASE_BRANCH=develop" >> $GITHUB_ENV
          echo "HEAD_BRANCH=${HEAD_BRANCH}" >> $GITHUB_ENV

      - name: Check if PR exists between base and head
        run: |
          PR_NUMBER=$(gh pr list --base $BASE_BRANCH --head $HEAD_BRANCH --json number -q ".[].number")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR description
        if: env.PR_NUMBER != ''
        run: |
          PR_DESCRIPTION=$(cat <<EOF
          
          ### 本番影響あり
          $(gh pr list --base $HEAD_BRANCH --state merged --search '-label:"1 本番影響なし"' --json url,author --template '{{range .}}- [ ] {{.url}} @{{.author.login}}{{"\n"}}{{end}}')

          ### 本番影響なし
          $(gh pr list --base $HEAD_BRANCH --state merged --search 'label:"1 本番影響なし"' --json url,author --template '{{range .}}- [ ] {{.url}} @{{.author.login}}{{"\n"}}{{end}}')

          EOF
          )

          gh pr edit "$PR_NUMBER" --body "$PR_DESCRIPTION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
